/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedQueryDocumentNode } from "graphql"
export type AddRecipe = {
  addRecipe: {
    id: string
  }
}
export type AddRecipeVariables = {
  recipe: {
    description?: string | null
    ingredientIDs?: string[] | null
    title: string
  }
}
export type AddRecipeDocument = TypedQueryDocumentNode<
  AddRecipe,
  AddRecipeVariables
>
