/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type deleteRecipe = {
    deleteRecipe: boolean;
};
export type deleteRecipeVariables = {
    recipeId: string;
};
