/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedQueryDocumentNode } from "graphql"
export type DeleteRecipe = {
  deleteRecipe: boolean
}
export type DeleteRecipeVariables = {
  recipeId: string
}
export type DeleteRecipeDocument = TypedQueryDocumentNode<
  DeleteRecipe,
  DeleteRecipeVariables
>
