/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedQueryDocumentNode } from "graphql"
export type GetRecipes = {
  recipes: {
    id: string
    title: string
    description: string | null
    ingredients: {
      id: string
      name: string
    }[]
  }[]
}
export type GetRecipesVariables = {}
export type GetRecipesDocument = TypedQueryDocumentNode<
  GetRecipes,
  GetRecipesVariables
>
