#!/usr/bin/env zsh

set -euo pipefail

here=$0:A:h

function sync {
    for arg; do
        local dest=${arg#$here/template/}
        mkdir -p $(dirname "$dest")
        cp "$arg" "$dest"
    done
}

function main {
    [[ -f package.json ]] && echo "error: package.json already exists!" && exit 1
    sync "$here"/template/package.json
    sync "$here"/template/packages/{lib,react,server}/package.json
    sync "$here"/template/packages/{lib,react,server}/tsconfig.json
    sync "$here"/template/packages/{lib,server}/index.ts
    sync "$here"/template/packages/react/index.tsx
    yarn
}

main
