#!/usr/bin/env bash

set -euo pipefail

function main {
    local repo="https://git.heroku.com/$1.git"
    git config remote.heroku.url >&- || git remote add heroku "$repo"
    yarn workspace @/react build
    git add .
    git add --force packages/server/public/_/*.{js,html}
    git commit -m Deploy
    git push heroku HEAD:master -f
}


if (( $# < 1 )); then
    echo "error: ./vendor/heroku [name of heroku app]" 1>&2
fi

main "$1"
