/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type addRecipe = {
    addRecipe: {
        id: string;
        title: string;
    };
};
export type addRecipeVariables = {
    recipe: ({
        title: string;
        description: string | null;
        isPublic: boolean;
        ingredientIDs: string[];
    }) | null;
};
