/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type getRecipes = {
    recipes: ({
        id: string;
        title: string;
        description: string | null;
        ingredients: ({
            id: string;
            name: string;
        })[];
    })[];
};
export type getRecipesVariables = {};
