/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type getRecipes = {
    recipes: ({
        id: string;
        title: string;
        ingredients: ({
            id: string;
            name: string;
        })[];
        user: {
            id: string;
            email: string;
        };
    })[];
};
export type getRecipesVariables = {};
