/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type addRecipe = {
    addRecipe: {
        id: string;
    };
};
export type addRecipeVariables = {
    recipe: {
        description?: string | null;
        ingredientIDs?: string[] | null;
        title: string;
    };
};
