name: workflows/test.yml
on:
  pull_request:
  push:
    branches:
      - master
      - deploy/production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/
        scope: '@Originate'

    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS}}-build-${{ hashFiles('**/yarn.lock') }}

    - name: Cache TypeScript output
      uses: actions/cache@v1
      with:
        path: template/ignored
        key: ignored

    - name: Debug
      run: |
        echo ${{ github.event_name }}
        echo ${{ github.ref }}

    - run: yarn --frozen-lockfile
      working-directory: template
    - run: yarn typecheck
      working-directory: template
    - run: yarn lint
      working-directory: template
