name: Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: cli tests
        run: yarn --frozen-lockfile && yarn test

      - run: yarn --frozen-lockfile
        working-directory: template

      - run: yarn typecheck
        working-directory: template

      - name: pre-fetch postgres docker image
        run: docker pull postgres:latest

      - run: yarn test
        working-directory: template

      - run: yarn lint
        working-directory: template
