name: Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn --frozen-lockfile
        working-directory: template
      - run: yarn typecheck
        working-directory: template
      - name: pre-fetch postgres docker image
        run: docker pull postgres:latest
      - run: yarn test
        working-directory: template
      - run: yarn lint
        working-directory: template
